/**
 * MCP Auth - Token Validation for MCP Server
 *
 * Validates JWT tokens from:
 * 1. Neon Auth (browser sessions)
 * 2. MCP tokens (generated via /api/auth/mcp-token)
 * 3. OAuth tokens (generated via /api/mcp/oauth/token)
 */

import * as jose from "jose"
// Note: getSql is only used for Neon Auth tokens, not MCP OAuth tokens
import { getSql } from "@/lib/db"
import { validateOrgApiKey, isExolarApiKey } from "@/lib/api-keys"

export interface MCPAuthContext {
  userId: number
  email: string
  organizationId: number
  organizationSlug: string
  orgRole: "owner" | "admin" | "viewer"
  userRole: "admin" | "viewer"
}

// Neon Auth JWKS endpoint
const NEON_AUTH_JWKS_URL =
  process.env.NEON_AUTH_JWKS_URL || "https://auth.neon.tech/.well-known/jwks.json"

// Secret for MCP tokens - should match the one in /api/auth/mcp-token
// IMPORTANT: Set MCP_TOKEN_SECRET in production environment
const MCP_TOKEN_SECRET = process.env.MCP_TOKEN_SECRET || process.env.DATABASE_URL

if (!MCP_TOKEN_SECRET) {
  console.warn("[mcp-auth] WARNING: MCP_TOKEN_SECRET not set. Using insecure fallback.")
}

const EFFECTIVE_SECRET = MCP_TOKEN_SECRET || "mcp-token-secret-INSECURE-FALLBACK"

let jwks: jose.JWTVerifyGetKey | null = null

async function getJWKS(): Promise<jose.JWTVerifyGetKey> {
  if (!jwks) {
    jwks = jose.createRemoteJWKSet(new URL(NEON_AUTH_JWKS_URL))
  }
  return jwks
}

/**
 * Validate a token from the Authorization header.
 * Supports both Neon Auth tokens and MCP tokens.
 * Returns the auth context or null if invalid.
 */
export async function validateMCPToken(
  authHeader: string | null
): Promise<MCPAuthContext | null> {
  if (!authHeader?.startsWith("Bearer ")) {
    return null
  }

  const token = authHeader.slice(7)
  if (!token) {
    return null
  }

  // First, check if it's an Exolar API key (exolar_* prefix)
  if (isExolarApiKey(authHeader)) {
    return validateApiKeyForMCP(authHeader)
  }

  // Then, try to validate as an MCP token (HS256 signed)
  const mcpContext = await validateMCPGeneratedToken(token)
  if (mcpContext) {
    return mcpContext
  }

  // If that fails, try Neon Auth token (RS256 signed via JWKS)
  return validateNeonAuthToken(token)
}

/**
 * Validate a token generated by /api/auth/mcp-token or /api/mcp/oauth/token
 */
async function validateMCPGeneratedToken(token: string): Promise<MCPAuthContext | null> {
  try {
    const secret = new TextEncoder().encode(EFFECTIVE_SECRET)

    const { payload } = await jose.jwtVerify(token, secret, {
      issuer: "exolar-qa",
      audience: "mcp-client",
    })

    // Check if it's our MCP token
    if (payload.type !== "mcp") {
      return null
    }

    const userId = parseInt(payload.sub as string, 10)
    const email = payload.email as string
    const organizationId = payload.org_id as number
    const organizationSlug = payload.org_slug as string
    const orgRole = payload.org_role as "owner" | "admin" | "viewer"

    if (!userId || !email || !organizationId) {
      console.error("[mcp-auth] MCP token missing required claims")
      return null
    }

    // Use user_role from JWT payload (included at token generation time)
    // This eliminates database queries on every MCP request, fixing random re-auth issues
    // caused by serverless cold starts, connection pool exhaustion, or network timeouts
    const userRole = (payload.user_role as "admin" | "viewer") || "viewer"

    return {
      userId,
      email,
      organizationId,
      organizationSlug,
      orgRole,
      userRole,
    }
  } catch {
    // Not a valid MCP token, will try Neon Auth next
    return null
  }
}

/**
 * Validate a Neon Auth token
 */
async function validateNeonAuthToken(token: string): Promise<MCPAuthContext | null> {
  try {
    // Verify JWT signature with Neon's JWKS
    const keySet = await getJWKS()
    const { payload } = await jose.jwtVerify(token, keySet)

    // Extract email from token
    const email = payload.email as string
    if (!email) {
      console.error("[mcp-auth] Token missing email claim")
      return null
    }

    // Look up user and org membership in database
    const sql = getSql()

    const result = await sql`
      SELECT
        u.id as user_id,
        u.email,
        u.role as user_role,
        u.default_org_id,
        o.id as organization_id,
        o.slug as organization_slug,
        om.role as org_role
      FROM dashboard_users u
      LEFT JOIN organizations o ON o.id = u.default_org_id
      LEFT JOIN organization_members om ON om.user_id = u.id AND om.organization_id = o.id
      WHERE u.email = ${email}
    `

    if (!result || result.length === 0) {
      console.error(`[mcp-auth] User not found for email: ${email}`)
      return null
    }

    const userInfo = result[0]

    if (!userInfo.organization_id) {
      console.error(`[mcp-auth] User ${email} has no organization assigned`)
      return null
    }

    return {
      userId: userInfo.user_id as number,
      email: userInfo.email as string,
      organizationId: userInfo.organization_id as number,
      organizationSlug: userInfo.organization_slug as string,
      orgRole: (userInfo.org_role as "owner" | "admin" | "viewer") || "viewer",
      userRole: userInfo.user_role as "admin" | "viewer",
    }
  } catch (error) {
    console.error("[mcp-auth] Token validation failed:", error)
    return null
  }
}

/**
 * Validate an Exolar API key (exolar_*) and return MCP auth context.
 * This allows API keys created in the dashboard to be used with the MCP endpoint.
 */
async function validateApiKeyForMCP(
  authHeader: string
): Promise<MCPAuthContext | null> {
  try {
    const apiKey = await validateOrgApiKey(authHeader)
    if (!apiKey) {
      console.error("[mcp-auth] API key validation failed")
      return null
    }

    // Look up organization and user details
    const sql = getSql()

    let result: Record<string, unknown>[] = []
    if (apiKey.createdBy) {
      result = await sql`
        SELECT
          u.id as user_id,
          u.email,
          u.role as user_role,
          o.id as organization_id,
          o.slug as organization_slug,
          om.role as org_role
        FROM organizations o
        LEFT JOIN dashboard_users u ON u.id = ${apiKey.createdBy}
        LEFT JOIN organization_members om ON om.user_id = u.id AND om.organization_id = o.id
        WHERE o.id = ${apiKey.organizationId}
      `
    }

    // If we can't find user details (key may not have created_by), use org-level defaults
    if (!result || result.length === 0 || !result[0].user_id) {
      // Fallback: get org info without user
      const orgResult = await sql`
        SELECT id, slug FROM organizations WHERE id = ${apiKey.organizationId}
      `
      if (!orgResult || orgResult.length === 0) {
        console.error(`[mcp-auth] Organization ${apiKey.organizationId} not found for API key`)
        return null
      }

      return {
        userId: 0, // System/API key user
        email: `apikey-${apiKey.name}@exolar.local`,
        organizationId: apiKey.organizationId,
        organizationSlug: orgResult[0].slug as string,
        orgRole: "viewer",
        userRole: "viewer",
      }
    }

    const userInfo = result[0]
    return {
      userId: userInfo.user_id as number,
      email: userInfo.email as string,
      organizationId: userInfo.organization_id as number,
      organizationSlug: userInfo.organization_slug as string,
      orgRole: (userInfo.org_role as "owner" | "admin" | "viewer") || "viewer",
      userRole: userInfo.user_role as "admin" | "viewer",
    }
  } catch (error) {
    console.error("[mcp-auth] API key validation error:", error)
    return null
  }
}
