import type { ComparisonResult } from "./types"

/**
 * Escape special Markdown characters in text
 */
function escapeMarkdown(text: string): string {
  return text.replace(/[|`*_{}[\]()#+\-.!<>]/g, "\\$&")
}

/**
 * Convert comparison result to Markdown format suitable for GitHub PR comments
 */
export function comparisonToMarkdown(comparison: ComparisonResult): string {
  const { baseline, current, summary, tests, performanceSummary } = comparison
  
  const newFailures = tests.filter((t) => t.diffCategory === "new_failure")
  const fixed = tests.filter((t) => t.diffCategory === "fixed")
  const newTests = tests.filter((t) => t.diffCategory === "new_test")
  const removed = tests.filter((t) => t.diffCategory === "removed_test")

  let md = `## 📊 Test Comparison Report\n\n`
  
  // Comparison metadata table
  md += `| | Baseline | Current |\n`
  md += `|---|---|---|\n`
  md += `| **Branch** | \`${baseline.branch}\` | \`${current.branch}\` |\n`
  md += `| **Commit** | \`${baseline.commitSha.slice(0, 7)}\` | \`${current.commitSha.slice(0, 7)}\` |\n`
  md += `| **Date** | ${new Date(baseline.startedAt).toLocaleString()} | ${new Date(current.startedAt).toLocaleString()} |\n`
  md += `| **Tests** | ${baseline.totalTests} | ${current.totalTests} |\n`
  md += `\n`

  // Summary section
  md += `### Summary\n\n`
  
  const passRateEmoji = summary.passRateDelta > 0 ? "📈" : summary.passRateDelta < 0 ? "📉" : "➡️"
  const passRateSign = summary.passRateDelta > 0 ? "+" : ""
  md += `- ${passRateEmoji} **Pass Rate**: ${summary.baselinePassRate.toFixed(1)}% → ${summary.currentPassRate.toFixed(1)}% (${passRateSign}${summary.passRateDelta.toFixed(1)}%)\n`
  
  if (summary.newFailures > 0) {
    md += `- 🔴 **New Failures**: ${summary.newFailures}\n`
  }
  if (summary.fixed > 0) {
    md += `- 🟢 **Fixed**: ${summary.fixed}\n`
  }
  if (summary.newTests > 0) {
    md += `- 🆕 **New Tests**: ${summary.newTests}\n`
  }
  if (summary.removedTests > 0) {
    md += `- ⛔ **Removed Tests**: ${summary.removedTests}\n`
  }
  
  // Performance summary if available
  if (performanceSummary) {
    md += `\n### Performance\n\n`
    const durationSign = summary.durationDeltaPercent > 0 ? "+" : ""
    md += `- **Duration Change**: ${durationSign}${summary.durationDeltaPercent.toFixed(1)}%\n`
    if (performanceSummary.regressions > 0) {
      md += `- 🐢 **Regressions**: ${performanceSummary.regressions} tests >${performanceSummary.threshold_pct}% slower\n`
    }
    if (performanceSummary.improvements > 0) {
      md += `- 🚀 **Improvements**: ${performanceSummary.improvements} tests >${performanceSummary.threshold_pct}% faster\n`
    }
  }
  md += `\n`

  // New failures details (collapsible)
  if (newFailures.length > 0) {
    md += `### 🔴 New Failures (${newFailures.length})\n\n`
    md += `<details>\n<summary>Click to expand</summary>\n\n`
    md += `| Test | File |\n`
    md += `|---|---|\n`
    newFailures.slice(0, 20).forEach((t) => {
      md += `| ${escapeMarkdown(t.testName)} | \`${t.testFile}\` |\n`
    })
    if (newFailures.length > 20) {
      md += `\n*... and ${newFailures.length - 20} more*\n`
    }
    md += `\n</details>\n\n`
  }

  // Fixed tests details (collapsible)
  if (fixed.length > 0) {
    md += `### 🟢 Fixed (${fixed.length})\n\n`
    md += `<details>\n<summary>Click to expand</summary>\n\n`
    md += `| Test | File |\n`
    md += `|---|---|\n`
    fixed.slice(0, 20).forEach((t) => {
      md += `| ${escapeMarkdown(t.testName)} | \`${t.testFile}\` |\n`
    })
    if (fixed.length > 20) {
      md += `\n*... and ${fixed.length - 20} more*\n`
    }
    md += `\n</details>\n\n`
  }

  // New tests (collapsible)
  if (newTests.length > 0) {
    md += `### 🆕 New Tests (${newTests.length})\n\n`
    md += `<details>\n<summary>Click to expand</summary>\n\n`
    md += `| Test | File |\n`
    md += `|---|---|\n`
    newTests.slice(0, 20).forEach((t) => {
      md += `| ${escapeMarkdown(t.testName)} | \`${t.testFile}\` |\n`
    })
    if (newTests.length > 20) {
      md += `\n*... and ${newTests.length - 20} more*\n`
    }
    md += `\n</details>\n\n`
  }

  // Footer
  md += `---\n`
  md += `*Generated by [Exolar E2E Dashboard](https://exolar.io) at ${new Date().toISOString()}*\n`

  return md
}

/**
 * Convert comparison result to JSON format for CI/programmatic use
 */
export function comparisonToJSON(comparison: ComparisonResult): string {
  const { baseline, current, summary, tests, performanceSummary } = comparison
  
  return JSON.stringify({
    generated_at: new Date().toISOString(),
    baseline: {
      branch: baseline.branch,
      commit_sha: baseline.commitSha,
      started_at: baseline.startedAt,
      total_tests: baseline.totalTests,
      passed: baseline.passed,
      failed: baseline.failed,
    },
    current: {
      branch: current.branch,
      commit_sha: current.commitSha,
      started_at: current.startedAt,
      total_tests: current.totalTests,
      passed: current.passed,
      failed: current.failed,
    },
    summary: {
      pass_rate_delta: summary.passRateDelta,
      new_failures: summary.newFailures,
      fixed: summary.fixed,
      new_tests: summary.newTests,
      removed_tests: summary.removedTests,
      duration_delta_percent: summary.durationDeltaPercent,
    },
    performance: performanceSummary ? {
      regressions: performanceSummary.regressions,
      improvements: performanceSummary.improvements,
      stable: performanceSummary.stable,
      threshold_pct: performanceSummary.threshold_pct,
    } : null,
    changes: {
      new_failures: tests
        .filter((t) => t.diffCategory === "new_failure")
        .map((t) => ({ name: t.testName, file: t.testFile })),
      fixed: tests
        .filter((t) => t.diffCategory === "fixed")
        .map((t) => ({ name: t.testName, file: t.testFile })),
      new_tests: tests
        .filter((t) => t.diffCategory === "new_test")
        .map((t) => ({ name: t.testName, file: t.testFile })),
      removed_tests: tests
        .filter((t) => t.diffCategory === "removed_test")
        .map((t) => ({ name: t.testName, file: t.testFile })),
    },
  }, null, 2)
}

/**
 * Trigger file download in browser
 * Creates a temporary anchor element and clicks it
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  
  try {
    const link = document.createElement("a")
    link.href = url
    link.download = filename
    link.style.display = "none"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  } finally {
    // Clean up the object URL after a delay to ensure download starts
    setTimeout(() => URL.revokeObjectURL(url), 1000)
  }
}

/**
 * Copy text to clipboard with fallback for older browsers
 * @returns true if successful, false if failed
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  // Modern Clipboard API
  if (navigator.clipboard && typeof navigator.clipboard.writeText === "function") {
    try {
      await navigator.clipboard.writeText(text)
      return true
    } catch (err) {
      console.warn("Clipboard API failed, trying fallback:", err)
    }
  }
  
  // Fallback for older browsers or when Clipboard API fails
  try {
    const textArea = document.createElement("textarea")
    textArea.value = text
    textArea.style.position = "fixed"
    textArea.style.left = "-9999px"
    textArea.style.top = "-9999px"
    document.body.appendChild(textArea)
    textArea.focus()
    textArea.select()
    
    const success = document.execCommand("copy")
    document.body.removeChild(textArea)
    return success
  } catch (err) {
    console.error("Fallback copy also failed:", err)
    return false
  }
}
