-- Migration 015: Add Vector Support for AI-Powered Analytics
-- Purpose: Enable pgvector and add embedding column for smart failure clustering
-- Date: 2026-01-12
-- Author: Claude Code

-- ============================================
-- STEP 1: Enable pgvector extension
-- ============================================
-- Note: Neon has pgvector pre-installed, just needs activation
CREATE EXTENSION IF NOT EXISTS vector;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_extension WHERE extname = 'vector'
  ) THEN
    RAISE EXCEPTION 'pgvector extension failed to install';
  END IF;
END $$;

-- ============================================
-- STEP 2: Add embedding column to test_results
-- ============================================
-- Using 768 dimensions for Gemini text-embedding-004
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'test_results'
    AND column_name = 'error_embedding'
  ) THEN
    ALTER TABLE test_results
    ADD COLUMN error_embedding vector(768);

    COMMENT ON COLUMN test_results.error_embedding IS
      'Vector embedding of error_message + stack_trace for similarity clustering. Generated by Gemini text-embedding-004.';
  END IF;
END $$;

-- ============================================
-- STEP 3: Create HNSW index for fast similarity search
-- ============================================
-- HNSW (Hierarchical Navigable Small Worlds) provides:
-- - Sub-millisecond query times
-- - Better recall than IVFFlat
-- - No need for periodic retraining

-- Partial index: only index failed tests (where embeddings exist)
CREATE INDEX IF NOT EXISTS idx_test_results_error_embedding_hnsw
ON test_results
USING hnsw (error_embedding vector_cosine_ops)
WHERE error_embedding IS NOT NULL;

-- Additional partial index for faster filtering by execution
CREATE INDEX IF NOT EXISTS idx_test_results_execution_embedding
ON test_results (execution_id)
WHERE error_embedding IS NOT NULL;

-- ============================================
-- STEP 4: Helper functions for vector operations
-- ============================================

-- Function: Find similar failures within an execution
CREATE OR REPLACE FUNCTION find_similar_failures(
  p_execution_id INTEGER,
  p_embedding vector(768),
  p_threshold FLOAT DEFAULT 0.1,
  p_limit INTEGER DEFAULT 10
)
RETURNS TABLE (
  id INTEGER,
  test_name TEXT,
  error_message TEXT,
  similarity FLOAT
)
LANGUAGE SQL
STABLE
AS $$
  SELECT
    tr.id,
    tr.test_name,
    tr.error_message,
    1 - (tr.error_embedding <=> p_embedding) as similarity
  FROM test_results tr
  WHERE tr.execution_id = p_execution_id
    AND tr.error_embedding IS NOT NULL
    AND tr.error_embedding <=> p_embedding < p_threshold
  ORDER BY tr.error_embedding <=> p_embedding
  LIMIT p_limit;
$$;

-- Function: Find similar failures across all executions (for historical analysis)
CREATE OR REPLACE FUNCTION find_similar_failures_global(
  p_organization_id INTEGER,
  p_embedding vector(768),
  p_threshold FLOAT DEFAULT 0.15,
  p_limit INTEGER DEFAULT 20
)
RETURNS TABLE (
  id INTEGER,
  execution_id INTEGER,
  test_name TEXT,
  error_message TEXT,
  similarity FLOAT,
  created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
AS $$
  SELECT
    tr.id,
    tr.execution_id,
    tr.test_name,
    tr.error_message,
    1 - (tr.error_embedding <=> p_embedding) as similarity,
    tr.created_at
  FROM test_results tr
  INNER JOIN test_executions te ON tr.execution_id = te.id
  WHERE te.organization_id = p_organization_id
    AND tr.error_embedding IS NOT NULL
    AND tr.error_embedding <=> p_embedding < p_threshold
  ORDER BY tr.error_embedding <=> p_embedding
  LIMIT p_limit;
$$;

COMMENT ON FUNCTION find_similar_failures IS
  'Find failures with similar error embeddings within a single execution. Used for smart clustering.';

COMMENT ON FUNCTION find_similar_failures_global IS
  'Find failures with similar error embeddings across all executions in an organization. Used for historical analysis.';

-- ============================================
-- STEP 5: Cluster cache tables
-- ============================================
-- Stores pre-computed clusters for faster dashboard loading
-- Can be populated lazily or via background job

CREATE TABLE IF NOT EXISTS failure_clusters (
  id SERIAL PRIMARY KEY,
  execution_id INTEGER NOT NULL REFERENCES test_executions(id) ON DELETE CASCADE,
  cluster_id INTEGER NOT NULL,
  centroid_embedding vector(768),
  representative_error TEXT,
  test_count INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  UNIQUE(execution_id, cluster_id)
);

-- Index for fast cluster lookup
CREATE INDEX IF NOT EXISTS idx_failure_clusters_execution
ON failure_clusters(execution_id);

-- Link table: which test_results belong to which cluster
CREATE TABLE IF NOT EXISTS failure_cluster_members (
  id SERIAL PRIMARY KEY,
  cluster_id INTEGER NOT NULL REFERENCES failure_clusters(id) ON DELETE CASCADE,
  test_result_id INTEGER NOT NULL REFERENCES test_results(id) ON DELETE CASCADE,
  distance_to_centroid FLOAT,

  UNIQUE(test_result_id)
);

CREATE INDEX IF NOT EXISTS idx_cluster_members_cluster
ON failure_cluster_members(cluster_id);

CREATE INDEX IF NOT EXISTS idx_cluster_members_result
ON failure_cluster_members(test_result_id);

-- Add comments
COMMENT ON TABLE failure_clusters IS
  'Pre-computed failure clusters for fast dashboard loading. Each cluster groups semantically similar failures.';

COMMENT ON TABLE failure_cluster_members IS
  'Maps test_results to their assigned failure cluster.';

-- ============================================
-- MIGRATION COMPLETE
-- ============================================
DO $$
BEGIN
  RAISE NOTICE 'Migration 015 completed: Vector support enabled for AI-powered analytics';
END $$;
